url=jdbc:postgresql://ep-fragrant-flower-adel6bm2-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb
username=neondb_owner
password=**************
driver=org.postgresql.Driver
changeLogFile=changelog.xml
